dataset: "eicu"
data_dir: "./data"
medical_task: "death" # Options: 'death', 'ventilation', 'sepsis'

# Model config
model: "medical_mlp"
model_output_dim: 1
model_input_channels: 1
num_classes: 2

VAE_input_dim: 268 # need double check
dropout_rate: 0.2
use_batch_norm: True

# FL configuration (for centralized baseline)
algorithm: "centralized"
client_num_in_total: 9
client_num_per_round: 5
comm_round: 100
global_epochs_per_round: 2
partition_method: "hospital"
partition_alpha: 0.1 # Not used for hospital partition

fedprox: False
fedprox_mu: 0.5

# VAE configuration (not used for centralized)
VAE: False
VAE_comm_round: 10
VAE_client_num_per_round: 9
VAE_local_epoch: 3

# VAE loss weights (not used)
VAE_re: 4.0
VAE_ce: 2.0
VAE_kl: 0.005
VAE_x_ce: 0.5

# VAE architecture (not used)
VAE_d: 128 # Hidden dimension
VAE_z: 16 # Latent dimension

# Noise parameters (not used)
VAE_mean: 0.0
VAE_std1: 0.0
VAE_std2: 0.005
noise_type: "Gaussian"

batch_size: 64
VAE_batch_size: 64
lr: 0.001
VAE_loss: "focal"
seed: 42

# Medical-specific settings
VAE_curriculum: False
VAE_adaptive: True
VAE_mixupdata: False # Disable mixup for tabular
VAE_alpha: 0.0 # No mixup
VAE_aug_batch_size: 64

# VAE balanced training (not used)
VAE_target_pos_ratio: 0.15

# Feature extraction for visualization
extract_features: true

# Other settings
sched: "no"
warmup_epochs: 5
record_tool: "wandb"
wandb_record: False
level: "INFO"
gpu_index: 0
instantiate_all: True
test: True

unseen_hospital_test: True
# the target hospital must be in selected hospital list!
target_hospital_id: 167

run_bootstrap_evaluation: True
bootstrap_seeds: 100
eval_test_size: 0.5
eval_val_size: 0.5
eval_metric: "auprc"

target_hospital_list: [167, 420, 199, 458, 252, 165, 148, 281, 449, 283]
auto_select_hospitals: True

# Evaluate only centralized for testing
eval_algorithms: ["centralized"]

# Output settings
output_path: "./output/evaluation_results"
create_evaluation_plots: True
