dataset: "eicu"
data_dir: "./data"
medical_task: "death" # Options: 'death', 'ventilation', 'sepsis', 'length'

# Model config
model: "medical_mlp"
model_output_dim: 1
model_input_channels: 1
num_classes: 2

VAE_input_dim: 268 # need double check
dropout_rate: 0.2
use_batch_norm: True

# FL configuration
algorithm: "FedAvg"
client_num_in_total: 9
client_num_per_round: 5
comm_round: 100
global_epochs_per_round: 5
partition_method: "hospital"

fedprox: False
fedprox_mu: 0.5

# VAE configuration
VAE: True
VAE_comm_round: 10
VAE_client_num_per_round: 9
VAE_local_epoch: 2

# VAE loss weights
VAE_re: 4.0
VAE_ce: 3.0
VAE_kl: 0.005
VAE_x_ce: 0.5

# VAE architecture
VAE_d: 128 # Hidden dimension
VAE_z: 8 # Latent dimension

# Noise parameters (DP protection)
VAE_mean: 0.0
VAE_std1: 0.0
VAE_std2: 0.005
noise_type: "Gaussian"

batch_size: 64
VAE_batch_size: 64
lr: 0.0002
wd: 0.001 # weight decay
VAE_loss: "focal"

loss_fn: "focal" # for federated model training & eval: CrossEntropy, focal or mse
focal_alpha: 0.85
focal_gamma: 2.0
seed: 42

# Medical-specific settings
VAE_curriculum: False
VAE_adaptive: True
VAE_mixupdata: False # Disable mixup for tabular
VAE_alpha: 0.0 # No mixup
VAE_aug_batch_size: 64

# VAE balanced training (VERY IMPORTANT!)
VAE_target_pos_ratio: 0.15

# Feature extraction for visualization
extract_features: true

# Other settings
sched: "no"
warmup_epochs: 5
record_tool: "wandb"
wandb_record: False
level: "INFO"
gpu_index: 0
instantiate_all: True
test: True

unseen_hospital_test: True
# the target hospital must be in selected hospital list!
target_hospital_id: 458

run_bootstrap_evaluation: True
bootstrap_seeds: 100
eval_test_size: 0.5
eval_val_size: 0.5
eval_metric: "auprc" # need change depending on classification/regression: loss/auprc

target_hospital_list: [167, 420, 199, 458, 252, 165, 148, 281, 449, 283]
auto_select_hospitals: True

eval_algorithms: ["centralized", "fedfed", "fedavg", "fedprox", "centralized"]

# Output settings
output_path: "./output/evaluation_results"
create_evaluation_plots: True
