dataset: "eicu"
data_dir: "./data"
medical_task: "death"

# Model config
model: "medical_mlp"
model_output_dim: 1
model_input_channels: 1
num_classes: 2

VAE_input_dim: 256
dropout_rate: 0.2
use_batch_norm: True

# FL configuration
algorithm: "FedAvg"
client_num_in_total: 10
client_num_per_round: 5
comm_round: 50
global_epochs_per_round: 1
partition_method: "hospital"
partition_alpha: 0.1

# FedAvg - NO VAE, NO FedProx
fedprox: False
VAE: False

batch_size: 64
lr: 0.001
seed: 42

# Other settings
sched: "no"
warmup_epochs: 5
record_tool: "wandb"
wandb_record: False
level: "INFO"
gpu_index: 0
instantiate_all: True
test: True

# Evaluation settings
unseen_hospital_test: True
target_hospital_id: 167
run_bootstrap_evaluation: True
bootstrap_seeds: 20
eval_test_size: 0.5
eval_val_size: 0.5 
eval_metric: "auprc"

target_hospital_list: [167, 420, 199, 458, 252, 165, 148, 281, 449, 283] 
auto_select_hospitals: True  

# Output settings
output_path: "./output/evaluation_results"
create_evaluation_plots: True